#
# paws dockerfile
#
# Build:
# sudo docker build -t paws:devel -f Dockerfile-devel .
#
# Run:
# sudo docker run -it --name paws-devel \
# -v /home/<user>/github/ws/:/home/paws/paws paws:devel bash
#

FROM centos:7

RUN useradd paws -u 1000
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
python get-pip.py && rm get-pip.py
RUN yum install -y git && yum clean all
RUN pip install --no-cache-dir \
git+https://github.com/rhpit/paws.git@devel
RUN yum remove -y git && yum clean all
USER paws
WORKDIR "/home/paws"
