#
# paws dockerfile
#
# Build:
# sudo docker build -t paws:devel -f Dockerfile-devel .
#
# Run:
# sudo docker run -it --name paws-devel \
# -v /home/<user>/github/ws/:/home/paws/paws paws:devel bash
#

FROM python:2
RUN git clone https://github.com/rhpit/paws.git -b devel /tmp/paws
RUN pip install --no-cache-dir /tmp/paws/.
RUN rm -rf /tmp/paws
RUN adduser --disabled-password --uid 1000 --gecos "" paws
USER paws
