#
# paws dockerfile
#
# Build:
# sudo docker build -t paws:latest -f Dockerfile-latest .
#
# Run:
# sudo docker run -it --name paws-<release> \
# -v /home/<user>/github/ws/:/home/paws/paws paws:<release> sh
#

FROM python:2
RUN pip install --no-cache-dir paws-cli
RUN adduser --disabled-password --uid 1000 --gecos "" paws
USER paws