#
# paws -- provision automated windows and services
# Copyright (C) 2016 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""Provision task."""

from logging import getLogger
from os.path import join
from ansible.errors import AnsibleRuntimeError
from paws.exceptions import NovaPasswordError, ProvisionError, SSHError
from paws.tasks import Tasks
from paws.util import cleanup, log_resources
from paws.util.decorators import handle_pre_tasks
from paws.providers import Provider

LOG = getLogger(__name__)


class Provision(Tasks):
    """Provision."""

    def __init__(self, args):
        """Constructor.

        :param args: Argparse arguments
        :type arg: class argparse.Namespace
        """
        super(Provision, self).__init__(args)
        self.credential_file = join(self.userdir, args.credentials)
        self.provider = Provider(self)

    @handle_pre_tasks
    def pre_tasks(self):
        """Perform any necessary pre task actions."""
        # Clean files generated by paws
        for provider_name in self.provider.provider_list:
            inst = self.provider.get_instance(provider_name)
            garbage = inst.garbage_collector()
            # TODO: what about multiple resources? we should or not
            # delete self.resources_paws ?
            # in a case that resources.paws exists and the provider running
            # is different then what described in resources.paws maybe the
            # providers should be responsible to preserve data and then append
            # new data into the file ? if resources.paws doesn't exist than
            # it is fine to just create and add new data to it?
            garbage.append(self.resources_paws)
            cleanup(garbage, self.userdir)

    def run(self):
        """The main method for provision. This method will call the providers
        module class to start calling provision method for the resources
        corresponding provider.
        """
        try:
            LOG.info("START: %s", self.__class__.__name__)

            # Save start time
            self.start()

            # Run provider action
            self.provider.run_action(self.__class__.__name__.lower())

            # Perform post tasks
            self.post_tasks()

        except SystemExit:
            raise SystemExit(1)
        except (AnsibleRuntimeError, NovaPasswordError, SSHError):
            raise ProvisionError
        except KeyboardInterrupt:
            LOG.warning("CTRL+C detected, interrupting execution")
            raise ProvisionError

    def post_tasks(self):
        """Perform any necessary post task actions."""
        # Save end time
        self.end()

        # Log system resources details to console
        log_resources(self.resources_paws, "provisioned")

        LOG.info("END: Provision, TIME: %dh:%dm:%ds",
                 self.hours, self.minutes, self.seconds)
